### DISCUSSION TITLE
Requests and Limits

### DISCUSSION THREAD

**Discussion by knweiss** [kubescape/kubescape#401] [General]
AFAICS kubescape currently reports missing requests and limits e.g. in `Deployment` manifests. However, Deployments are not the only way to set requests and limits. For example, it is also possible to set default requests and limits for all pods in a namespace with a `LimitRange` manifest:

```
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: default
spec:
  limits:
  - default:
      cpu: 15m
      memory: 105M
    defaultRequest:
      cpu: 15m
      memory: 105M
---
```
Thus requests and limits in a deployment are sufficient but not necessary.

So I wonder if kubescape should only report missing requests and limits if there are actual pods running without them.

Thoughts?
