### ISSUE TITLE
unable to use kubescape with host scanner on GKE

### ISSUE THREAD

**Issue by tomekzielins** [kubescape/kubescape#1077]
# Description
Unable to use host scanner flag "-enable-host-scan" in GKE. 

# Environment
OS: ` 1.24.8-gke.2000 `
Version: `v2.0.183 ` 
 
# Steps To Reproduce
1. Create GKE private cluster on GCP
2. Install most recent version of Kubescape 
3. Start scan with "kubescape scan --enable-host-scan"

# Expected behavior
All information gathered by kubescape with --enable-host-scane flag available to validate framewrok controls. 

# Actual Behavior
Error are displayed:
[info] Requesting Host scanner data
◒[warning] the server is currently unable to handle the request (get pods http:host-scanner-4tgcc:7888)
[info] Unknown host scanner version
◓[error] failed to get data. path: /kubeletConfigurations; podName: host-scanner-4tgcc; error: the server is currently unable to handle the request (get pods http:host-scanner-4tgcc:7888)
◑[error] failed to get data. path: /kubeletConfigurations; podName: host-scanner-btmnv; error: the server is currently unable to handle the request (get pods http:host-scanner-btmnv:7888)
◐[error] failed to get data. path: /kubeletCommandLine; podName: host-scanner-btmnv; error: the server is currently unable to handle the request (get pods http:host-scanner-btmnv:7888)
.....

# Additional context
During tool execution dedicated namespace and pods are created for host-scanner.  Looks like these pods gather required information as I can query them with curl:
$ curl 10.0.64.58:7888/cloudProviderInfo
{"providerMetaDataAPIAccess":true}
$ curl 10.0.64.58:7888/osRelease
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
....

Following errors can be found in pod logs: 

Starting Kubescape cluster node host scanner service
Host scanner service build version: v1.0.39
{"level":"warn","ts":"2023-02-03T14:37:34.630138465Z","msg":"Not implemented"}
{"level":"info","ts":"2023-02-03T14:37:34.630186292Z","msg":"Listening...","port":7888}
{"level":"debug","ts":"2023-02-03T14:37:35.485074394Z","msg":"In filterNLogHTTPErrors","method":"GET","requestURI":"/kernelVersion","remoteAddr":"10.0.64.60:54274"}
{"level":"debug","ts":"2023-02-03T14:37:35.485217994Z","msg":"reading file on host file system","path":"/host_fs/proc/version"}
[negroni] 2023-02-03T14:37:35Z | 200 |   344.768µs | 10.0.64.60:7888 | GET /kernelVersion
{"level":"debug","ts":"2023-02-03T14:37:37.08216136Z","msg":"In filterNLogHTTPErrors","method":"GET","requestURI":"/kernelVersion","remoteAddr":"10.0.64.60:54280"}
{"level":"debug","ts":"2023-02-03T14:37:37.082298568Z","msg":"reading file on host file system","path":"/host_fs/proc/version"}
[negroni] 2023-02-03T14:37:37Z | 200 |   336.96µs | 10.0.64.60:7888 | GET /kernelVersion
.....

**Comment by yuleib** [comment]
@tomekzielins Thank you for pointing us to this issue. 
we will try to reprodoce it from our side and will send a fix soon.

**Comment by yuleib** [comment]
Hey @tomekzielins , I've tried to do my best with reproducing the issue you saw with Host-Scanner without any luck. 
I've demosrated the same GKE env. you have and i ran the latest kubescape release, kubescape results successfully generated with no issue. 

Do you use some kind of VPC or VPN in your cluster (for access and security improvement )?

**Comment by tomekzielins** [comment]
For my various tests I have run cluster with almost default settings. I use Shared VPC.

**Comment by yuleib** [comment]
@tomekzielins is it host vpc or hosted vpc ?

**Comment by SMR39** [comment]
running into same issues ! 

using shared vpc too - which means its the VPC is created in a different google project (HOST project) and GKE clusters are created in service projects. 

more info [here](https://cloud.google.com/vpc/docs/shared-vpc)

**Comment by tomekzielins** [comment]
Shared VPC -> https://cloud.google.com/vpc/docs/shared-vpc 
This is a type of VPC created in a host project, which can be shared between multiple other (service) projects. 
GKE Cluster is created in one of service projects. 
What is also important we use private clusters, this means that worker nodes do not have public endpoints and communication between nodes and master node uses private IPs only. 
You can use similar command to create such cluster: 

gcloud container clusters create "cluster-1" \
--zone="us-central1-c" \
--project=[project ID] \
--machine-type "e2-small" \
--image-type "COS_CONTAINERD" \
--enable-ip-alias \
--enable-private-nodes \
--master-ipv4-cidr "172.16.0.0/28" \
--num-nodes "3" \
--network="projects/[host_project_ID]/global/networks/[shared_vpc_name]" \
--subnetwork="projects/[host_project_ID]/regions/[region]/subnetworks/[subnetwork_name]" \
--cluster-secondary-range-name [subnetwork_secondary_range_name_for_pods] \
--services-secondary-range-name [subnetwork_secondary_range_name_for_service] \
--default-max-pods-per-node "110" \
--no-enable-master-authorized-networks \
--enable-autoupgrade \
--enable-autorepair \
--node-locations "us-central1-c"

**Comment by kevin-shelaga** [comment]
I believe the issue is using a private cluster, not the shared VPC. Using a private cluster with your own VPC or the default still results in the same failed host scanner result. Is the host scanner calling the kube api server? If so we will need to open firewall rules for the port.

**Comment by tomekzielins** [comment]
Indeed the problem was with firewall rules. I had to open port TCP 7888 between GKE control plane IP range and IP range dedicated for nodes. It would be a good idea to add this info to kubescape manual.

**Comment by yuleib** [comment]
@tomekzielins i'm glad that issue resolved :) 
will be added as part of the readme file / release notes for kubescape.

**Comment by kevin-shelaga** [comment]
@tomekzielins im still seeing issues after adding 7888, do you have other ports added which might of helped?

**Comment by matthyx** [comment]
@kevin-shelaga do you mind helping us in testing a potential fix?

Could you run `kubescape` with the following option:
```
kubescape scan --enable-host-scan --host-scan-yaml hostsensor.yaml
```

With this content for `hostsensor.yaml`:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: kubescape-host-scanner
    k8s-app: kubescape-host-scanner
    kubernetes.io/metadata.name: kubescape-host-scanner
    tier: kubescape-host-scanner-control-plane
  name: kubescape-host-scanner
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: host-scanner
  namespace: kubescape-host-scanner
  labels:
    app: host-scanner
    k8s-app: kubescape-host-scanner
    otel: enabled
spec:
  selector:
    matchLabels:
      name: host-scanner
  template:
    metadata:
      labels:
        name: host-scanner
    spec:
      tolerations:
      # this toleration is to have the DaemonDet runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: host-sensor
        image: quay.io/kubescape/host-scanner:v1.0.45
        env:
        - name: OTEL_COLLECTOR_SVC
          value: "otel-collector.kubescape:4317"
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: true
          procMount: Unmasked
        ports:
          - name: scanner # Do not change port name
            containerPort: 7888
            protocol: TCP
        resources:
          limits:
            cpu: 0.1m
            memory: 200Mi
          requests:
            cpu: 1m
            memory: 200Mi
        volumeMounts:
        - mountPath: /host_fs
          name: host-filesystem
        readinessProbe:
          httpGet:
            path: /kernelVersion
            port: 7888
            initialDelaySeconds: 1
            periodSeconds: 1
      terminationGracePeriodSeconds: 120
      dnsPolicy: ClusterFirstWithHostNet
      automountServiceAccountToken: false
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host-filesystem
      hostPID: true
      hostIPC: true
```

And let me know if that solves your connectivity issue?
