### ISSUE TITLE
Some controls added in exceptions.json file are ignored and fail

### ISSUE THREAD

**Issue by inakizorrilla** [kubescape/kubescape#1125]
# Description

Hi everyone
I'm unable to make kubescape ignore some controls that I added to my exceptions.json file when scanning a deployment. I get the same result with a non-kustomized deployment.

For example, in my case, [C-0211](https://hub.armosec.io/docs/c-0211) and [C-0237](https://hub.armosec.io/docs/c-0237).

# Environment
OS: `Ubuntu 22.04 in WSL and Ubuntu 20.04 in Azure Container Instance (agent) ` 
Version: `2.2.0, 2.2.3` (tried both of them) 
 
# Steps To Reproduce
- Create a `exceptions.json` and a `controls-inputs.json` file, fill them (as shown in Additional context)
- Use either local or remote artifacts
- Execute command shown in Additional context

# Expected behavior

The exceptions are ignored

# Actual Behavior

Theese two particular exceptions are not ignored:
-  CIS-5.7.3 Apply Security Context to Your Pods and ...
- Check if signature exists
```
Controls: 211 (Failed: 8, Passed: 197, Action Required: 6)
Failed Resources by Severity: Critical — 0, High — 2, Medium — 4, Low — 2

+----------+-------------------------------------------------------+------------------+---------------+-------------------+
| SEVERITY |                     CONTROL NAME                      | FAILED RESOURCES | ALL RESOURCES |   % RISK-SCORE    |
+----------+-------------------------------------------------------+------------------+---------------+-------------------+
| High     | Forbidden Container Registries                        |        0         |       1       | Action Required * |
| High     | Resources memory limit and request                    |        0         |       1       | Action Required * |
| High     | Applications credentials in configuration files       |        0         |       1       | Action Required * |
| High     | Resources CPU limit and request                       |        0         |       1       | Action Required * |
| High     | CIS-5.7.3 Apply Security Context to Your Pods and ... |        1         |       1       |       100%        |
| High     | Verify image signature                                |        0         |       1       | Action Required * |
| High     | Check if signature exists                             |        1         |       1       |       100%        |
| Medium   | Ingress and Egress blocked                            |        1         |       1       |       100%        |
| Medium   | Configured liveness probe                             |        1         |       1       |       100%        |
| Medium   | CIS-5.1.4 Minimize Container Registries to only th... |        0         |       1       | Action Required * |
| Medium   | CIS-5.4.1 Prefer using secrets as files over secre... |        1         |       1       |       100%        |
| Medium   | CIS-5.7.2 Ensure that the seccomp profile is set t... |        1         |       1       |       100%        |
| Low      | Label usage for resources                             |        1         |       1       |       100%        |
| Low      | K8s common labels usage                               |        1         |       1       |       100%        |
+----------+-------------------------------------------------------+------------------+---------------+-------------------+
|          |                   RESOURCE SUMMARY                    |        1         |       2       |      17.87%       |
+----------+-------------------------------------------------------+------------------+---------------+-------------------+
FRAMEWORKS: AllControls (risk: 8.86), NSA (risk: 7.59), MITRE (risk: 0.00), AllControls (risk: 8.86), ArmoBest (risk: 11.11), cis-eks-t1.2.0 (risk: 14.29), cis-v1.23-t1.0.1 (risk: 55.17), DevOpsBest (risk: 19.51), MITRE (risk: 0.00), NSA (risk: 7.59)

* Control configurations are empty
[success] Scan results saved. filename: report.xml

Overall risk-score (0- Excellent, 100- All failed): 18
```

# Additional context

Executed command:
```
kustomize build . | kubescape scan - --format junit --exclude-namespaces kube-system,kube-public --use-artifacts-from ./artifacts/ --exceptions ./exceptions.json --fail-threshold 40 --severity-threshold high --controls-config ./controls-inputs.json
```

Exceptions file:
```
[
    {
    "name": "my-framework-exceptions",
    "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
    "resources": [
        {
            "designatorType": "Attributes",
            "attributes": {
                "labels": ".*"
            }
        }
    ],
    "posturePolicies": [
        {
            "frameworkName": "cis-eks-t1.2.0"
        }
    ]
    },
    {
        "name": "my-framework-exception-0004",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0004"
            }
        ]
    },
    {
        "name": "my-framework-exception-0012",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0012"
            }
        ]
    },
    {
        "name": "my-framework-exception-0055",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0055"
            }
        ]
    },
    {
        "name": "my-framework-exception-0076",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0076"
            }
        ]
    },
    {
        "name": "my-framework-exception-0193",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0193"
            }
        ]
    },
    {
        "name": "my-framework-exception-0202",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0202"
            }
        ]
    },
    {
        "name": "my-framework-exception-0211",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "disable"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0211"
            }
        ]
    },
    {
        "name": "my-framework-exception-0225",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0225"
            }
        ]
    },
    {
        "name": "my-framework-exception-0236",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0236"
            }
        ]
    },
    {
        "name": "my-framework-exception-0237",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
                {
                    "designatorType": "Attributes",
                    "attributes": {
                        "labels": ".*"
                    }
                }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0237"
            }
        ]
    }
]
```

Controls file:
```
{
  "cpu_limit_max": [],
  "cpu_limit_min": [],
  "cpu_request_max": [],
  "cpu_request_min": [],
  "imageRepositoryAllowList": [
    ".*azurecr.io"],
  "insecureCapabilities": [
    "SETPCAP",
    "NET_ADMIN",
    "NET_RAW",
    "SYS_MODULE",
    "SYS_RAWIO",
    "SYS_PTRACE",
    "SYS_ADMIN",
    "SYS_BOOT",
    "MAC_OVERRIDE",
    "MAC_ADMIN",
    "PERFMON",
    "ALL",
    "BPF"
  ],
  "k8sRecommendedLabels": [
    "app.kubernetes.io/name",
    "app.kubernetes.io/instance",
    "app.kubernetes.io/version",
    "app.kubernetes.io/component",
    "app.kubernetes.io/part-of",
    "app.kubernetes.io/managed-by",
    "app.kubernetes.io/created-by"
  ],
  "listOfDangerousArtifacts": [
    "bin/bash",
    "sbin/sh",
    "bin/ksh",
    "bin/tcsh",
    "bin/zsh",
    "usr/bin/scsh",
    "bin/csh",
    "bin/busybox",
    "usr/bin/busybox"
  ],
  "max_critical_vulnerabilities": [
    "5"
  ],
  "max_high_vulnerabilities": [
    "10"
  ],
  "memory_limit_max": [],
  "memory_limit_min": [],
  "memory_request_max": [],
  "memory_request_min": [],
  "publicRegistries": [],
  "recommendedLabels": [
    "app",
    "tier",
    "phase",
    "version",
    "owner",
    "env"
  ],
  "sensitiveInterfaces": [
    "nifi",
    "argo-server",
    "weave-scope-app",
    "kubeflow",
    "kubernetes-dashboard",
    "jenkins",
    "prometheus-deployment"
  ],
  "sensitiveKeyNames": [
    "aws_access_key_id",
    "aws_secret_access_key",
    "azure_batchai_storage_account",
    "azure_batchai_storage_key",
    "azure_batch_account",
    "azure_batch_key",
    "secret",
    "key",
    "password",
    "pwd",
    "token",
    "jwt",
    "bearer",
    "credential"
  ],
  "sensitiveValues": [
    "BEGIN \\w+ PRIVATE KEY",
    "PRIVATE KEY",
    "eyJhbGciO",
    "JWT",
    "Bearer",
    "_key_",
    "_secret_"
  ],
  "sensitiveValuesAllowed": [],
  "servicesNames": [
    "nifi-service",
    "argo-server",
    "minio",
    "postgres",
    "workflow-controller-metrics",
    "weave-scope-app",
    "kubernetes-dashboard"
  ],
  "untrustedRegistries": [],
  "wlKnownNames": [
    "coredns",
    "kube-proxy",
    "event-exporter-gke",
    "kube-dns",
    "17-default-backend",
    "metrics-server",
    "ca-audit",
    "ca-dashboard-aggregator",
    "ca-notification-server",
    "ca-ocimage",
    "ca-oracle",
    "ca-posture",
    "ca-rbac",
    "ca-vuln-scan",
    "ca-webhook",
    "ca-websocket",
    "clair-clair"
  ]
}
```
I've also tried adding the exceptions by their name but I got the same result. And also adding the execeptions as a list like so:
```
{
        "name": "my-control-exceptions-list",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
            {
                "designatorType": "Attributes",
                "attributes": {
                    "kind": ".*"
                }
            }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0004"
            },
            {
                "controlID": "C-0012"
            },
            {
                "controlID": "C-0055" 
            },
            {
                "controlID": "C-0076" 
            },
            {
                "controlID": "C-0193" 
            },
            {
                "controlID": "C-0202" 
            },
            {
                "controlID": "C-0211"
            },
            { 
                "controlID": "C-0225" 
            },
            { 
                "controlID": "C-0236" 
            },
            { 
                "controlID": "C-0237" 
            }
        ]
    }
```
Even adding my exceptions to the exceptions.json file downloaded with the artifacts (when using local ones) returns the same result.

Thank you!

**Comment by dwertent** [comment]
Thank you @inakizorrilla for reporting, I will try to reproduce this.
Can you please share the repository you tried testing? (if it is public...)

**Comment by inakizorrilla** [comment]
I am afraid I cannot share the repo, but I can paste the obfuscated output of the scanned kustomize build.

<details>
  <summary>Kustomize build file</summary>
 
  
  ```
apiVersion: v1
kind: Service
metadata:
    name: myappname
    namespace: ${KUBERNETES_NAMESPACE}
spec:
    ports:
    - port: 8080
    selector:
        app: myappname
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: myappname
    namespace: ${KUBERNETES_NAMESPACE}
spec:
    minReadySeconds: 5
    replicas: 1
    selector:
        matchLabels:
            app: myappname
    strategy:
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 0
    template:
        metadata:
            labels:
                aadpodidbinding: ${POD_IDENTITY_ID}
                app: myappname
        spec:
            containers:
            - env:
                - name: APP_ENVIRONMENT
                  value: Development
             image: ${CONTAINER_REGISTRY_NAME}.azurecr.io/myappname
             imagePullPolicy: Always
             name: myappname
             ports:
             - containerPort: 8080
             readinessProbe:
                 failureThreshold: 3
                 httpGet:
                     path: /health
                     port: 8080
                     scheme: HTTP
                 initialDelaySeconds: 5
                 periodSeconds: 5
                 successThreshold: 1
                 timeoutSeconds: 1
             resources:
                 limits:
                     cpu: 300m
                     ephemeral-storage: 500Mi
                     memory: 500Mi
                 requests:
                     cpu: 50m
                     ephemeral-storage: 100Mi
                     memory: 100Mi
             securityContext:
                 allowPrivilegeEscalation: false
                 capabilities:
                     drop:
                     - all
                 readOnlyRootFilesystem: true
                 runAsGroup: 30000
                 runAsUser: 10000
             volumeMounts:
             - mountPath: /tmp
               name: tmp
             - mountPath: /mnt/secrets-store###1
               name: secrets-store###1
               readOnly: true
       volumes:
       - emptyDir: {}
         name: tmp
       - csi:
             driver: secrets-store.csi.k8s.io
             readOnly: true
             volumeAttributes:
                 secretProviderClass: azure-kv-secretprovider###1
          name: secrets-store###1
  ```
</details>

If you need anything else please ask me.
Thank you for your time!
