### ISSUE TITLE
Error in running kubescape fix command

### ISSUE THREAD

**Issue by anubhav06** [kubescape/kubescape#1255]
# Description
Unable to use the kubescape's fix command.
Running `kubescape fix output.json` shows an error `[fatal] Cannot Encode into YAML`

# Environment
OS:  `Ubuntu 20.04.4 LTS` 
Kubescape Version:  `v2.3.5`
 
# Steps To Reproduce
1. Run `kubescape scan /path/to/manifest-files-repo --format json --output output.json`
2. Run `kubescape fix output.json`
3. Enter  `y` when asked `Would you like to apply the changes to the files above? [y|n]:` 

# Expected behavior
Running `kubescape fix output.json` should fix the misconfigurations in the files

# Actual Behavior
We get an error: `[fatal] Cannot Encode into YAML` as shown below: 

![image](https://github.com/kubescape/kubescape/assets/43821031/eca4dd37-1680-4fcf-a5e0-ed405422dc50)

Upon digging further, I found that the error message we get from [here ](https://github.com/kubescape/kubescape/blob/master/core/pkg/fixhandler/yamlhelper.go#L101) is:
`error debugging node, yaml: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS, but got document start`

 ______________________________________________________________________________________________________________________________

**Comment by matthyx** [comment]
hi @anubhav06 do you mind sharing the file `docker-build.yaml`?

**Comment by anubhav06** [comment]
Sure, here is the `docker-build.yaml` file:
```
apiVersion: v1
kind: Pod
metadata:
  name: build-image
spec:
  restartPolicy: OnFailure
  containers:
  - name: docker-build
    image: docker
    env:
    - name: REGISTRY_PORT
      value: #"30000"
    command: ["sh", "-c"]
    args:
    - |
      apk add --no-cache git &&
      mkdir /workspace &&
      git clone https://github.com/jpetazzo/container.training /workspace &&
      docker build -t localhost:$REGISTRY_PORT/worker /workspace/dockercoins/worker &&
      docker push localhost:$REGISTRY_PORT/worker
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
```

**Comment by matthyx** [comment]
Hmm, works for me:
```
[info] Reading report file...
[info] The following changes will be applied:
File: /tmp/bug/docker-build.yaml
Resource: build-image
Kind: Pod
Changes:
        1) spec.containers[0].securityContext.runAsNonRoot = true
        2) spec.containers[0].securityContext.allowPrivilegeEscalation = false
        3) spec.containers[0].volumeMounts[0].readOnly = true
        4) spec.containers[0].securityContext.readOnlyRootFilesystem = true

------

Would you like to apply the changes to the files above? [y|n]: 
y
[info] Fixed resources in 1 files.
```

I wonder if it's not because of a mixed end of line encoding within the YAML file, since you're on Windows...
Do you mind calling `dos2unix` on the file before starting again?

**Comment by anubhav06** [comment]
When I tried to fix the individual file like you did, then it worked even for me. 
Upon further digging in the repo which I am scanning, I found that the error is coming from YAML files which start with a document separator (`---`)

Consider the below file `dockercoins.yaml`, if you try to run the fix command on it, you will get an error:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasher
  name: hasher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - image: dockercoins/hasher:v0.1
        name: hasher
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher
  name: hasher
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rng
  name: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - image: dockercoins/rng:v0.1
        name: rng
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rng
  name: rng
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - image: dockercoins/webui:v0.1
        name: webui
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
  name: webui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockercoins/worker:v0.1
        name: worker

```

However, when we remove the top-most separator in the YAML file (at Line -1), then the error is gone and fix command is able to fix the file.
