### ISSUE TITLE
Exception on label is ignored with a resource that has multiple labels

### ISSUE THREAD

**Issue by martijnvdp** [kubescape/kubescape#1278]
# Description
Exception on label is ignored with a resource that has multiple labels

# Environment
OS: ` UBUNTU 22.04` 
Version: ` v2.3.7` 
 
# Steps To Reproduce

1. create a resource.yaml with a resource to scan with errors like
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  labels:
    another-label: test
    exclude-from-kubescape: yes
```
2. scan the file which should result in 2 failures
kubescape scan resource.yaml --verbose --format junit 
 | Medium   | Cluster internal networking | https://hub.armosec.io/docs/c-0054 |                      |
 | Low      | Network mapping             | https://hub.armosec.io/docs/c-0049 |
3. then i try to create an exception based on the label in a new json file exception.json
```
  {
    "name": "exclude-test",
    "policyType": "postureExceptionPolicy",
    "actions": ["alertOnly"],
    "resources": [
      {
        "designatorType": "Attributes",
        "attributes": {
          "exclude-from-kubescape": "yes"
        }
      }
    ],
    "posturePolicies": [
      {
        "controlID": "C-0054"
      },
      {
        "controlID": "C-0049"
      }
    ]
  }
  ```
4. rescan using this json gives same result 2 failures:
 `kubescape scan resource.yaml --verbose --format junit --exceptions .\exception.json`
5. remove one label from the resource yaml so it only has the exception label and save
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  labels:
    exclude-from-kubescape: yes
```
6. than i do a rescan `kubescape scan resource.yaml --verbose --format junit --exceptions .\exception.json`
and its excluded correctly
    

# Expected behavior
i expected to be able to exclude the resource when it has also other labels than the exception label
the examples indicate that this should work https://github.com/kubescape/kubescape/tree/master/examples/exceptions
# Actual Behavior
exception only seems to work when the resource only has 1 exception label
