### ISSUE TITLE
Would like to see Cilium CRDs recognized by Kubescape/rego.

### ISSUE THREAD

**Issue by distributethe6ix** [kubescape/kubescape#1397]
## Overview
I would like to have the ability to run `kubescape scan control C-0260 -v` and have kubescape recognize the CiliumNetworkPolicy CRD. 

Here's a sample YAML:
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: deny-all
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  ingress: []
  egress: []
```

## Problem
Kubernetes offers a simple NetworkPolicy CRD but is limited in functionality and doesn't completely provide all the necessary controls and policy capabilities that most CNIs would. This is a base functionality. If a Platform Engineer leverages the Cilium CNI, and uses its native CRDs, Kubescape won't recognize this configuration.

## Solution
If Kubescape's rego configuration can honour the CiliumNetworkPolicy CRD, this will allow for C-0260 to pass, with a simple Deny-all policy.
