### ISSUE TITLE
Non-Root container false positive

### ISSUE THREAD

**Issue by jankoh** [kubescape/kubescape#1606]
# Description

We are recently getting non-root-container alerts
```html
Name: backup-internal

ApiVersion: batch/v1
Kind: CronJob
Name: backup-internal
Namespace:

Severity | Name | Docs | Assisted Remediation
-- | -- | -- | --
Medium | Non-root containers | C-0013 | spec.jobTemplate.spec.template.spec.containers[0].securityContext.runAsGroup=1000

Name: backup-internal
ApiVersion: batch/v1

Kind: CronJob

Name: backup-internal

Namespace:

Severity	Name	Docs	Assisted Remediation
Medium	Non-root containers	[C-0013](https://hub.armosec.io/docs/c-0013)	
spec.jobTemplate.spec.template.spec.containers[0].securityContext.runAsGroup=1000
``` 

While it is true, that we don't set `runAsGroup` in the container's security context, we set `runAsNonRoot` in the pod's security context. 

Documentation states:

Remediation
If your application does not need root privileges, make sure to define the runAsUser or runAsGroup under the PodSecurityContext or container securityContext and use user ID 1000 or higher, or make sure that runAsNonRoot is true.

In my understanding we should meet the criteria in the last sentence.

Do I mis-understand the documentation? Or is this a false-positive and probably a bug?

# Environment
OS: Alpine Linux (Container environment)
Version: 3.18
 
# Steps To Reproduce
- This is one of the incriminated manifests
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-internal
  annotations:
    
  labels:
    app.kubernetes.io/name: db-rv-tool
    helm.sh/chart: db-rv-tool-0.2.0
    app.kubernetes.io/instance: rv-tool
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "master"
    alerts.n4.de/workload: high-cpu    
spec:
  schedule: 45 */12 * * *
  timeZone: Europe/Berlin
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          name: backup-internal
          annotations:
            checksum/config: b5b96799c8c23ba72612c8ae14f0bdaee919a664a6bcf53d95bd145d0d7c1a6b
            checksum/secret: 87d02c00a9a573b759075f2c5751db236f8815641b1152ecacb03a30959a5831
            kubectl.kubernetes.io/default-container: db-rv-tool
            
            
          labels:
            app.kubernetes.io/name: db-rv-tool
            helm.sh/chart: db-rv-tool-0.2.0
            app.kubernetes.io/instance: rv-tool
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/version: "master"
            networkpolicies.n4.de/access-from-ingress: deny
            networkpolicies.n4.de/access-from-prometheus: deny
            networkpolicies.n4.de/access-from-own-namespace: deny
            
            networkpolicies.n4.de/access-to-own-namespace: allow
            networkpolicies.n4.de/access-to-prometheus-pushgateway: allow
            networkpolicies.n4.de/access-to-world: allow
            alerts.n4.de/workload: high-cpu
        spec:
          imagePullSecrets:
          - name: n4r-rv-tool-pullsecret
          securityContext:
            runAsNonRoot: true
          containers:
          - name: backup-internal
            image: registry.n4group.eu/team-elster/helper/postgres-v15-backup:v0.15.1
            imagePullPolicy: Always
            command:
            - "backupandrestore"
            - "-b"
            - "-e"
            - "PUSH"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - all
              privileged: false
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: "250m"
                ephemeral-storage: "256Mi"
                memory: "256M"
              limits:
                cpu: "750m"
                ephemeral-storage: "256Mi"
                memory: "1Gi"
            volumeMounts:
            - mountPath: /tmp
              name: n4-tmp
            - mountPath: /home/bnr
              name: home-bnr
            envFrom:
            - secretRef:
                name: n4c-db-rv-tool-backup-postgres-internal
            startupProbe:
              exec:
                command:
                - cat
                - /tmp/backupandrestore.pid
              failureThreshold: 5
              periodSeconds: 3
            livenessProbe:
              exec:
                command:
                - cat
                - /tmp/backupandrestore.pid
              initialDelaySeconds: 15
              periodSeconds: 3
              failureThreshold: 3
            readinessProbe:
              exec:
                command:
                - cat
                - /tmp/backupandrestore.pid
              initialDelaySeconds: 15
              periodSeconds: 3
          volumes:
          - emptyDir: {}
            name: n4-tmp
          - emptyDir: {}
            name: home-bnr
          restartPolicy: Never
          priorityClassName: n4-medium-plus
```

# Expected behavior
Non-root containers should not be incriminated. If setting runAsGroup is expected, the documentation seems misleading, at least to me.

# Actual Behavior
We get a false-positive for C-0013
