### ISSUE TITLE
Synchronizer is failing with resource not found error

### ISSUE THREAD

**Issue by headyj** [kubescape/kubescape#1693]
# Description
synchronizer is failing with the following error:
```
{"level":"error","ts":"2024-06-05T13:18:14Z","msg":"giving up watch","error":"the server could not find the requested resource","resource":"cilium.io/v2, Resource=ciliumnetworkpolicies"}
{"level":"error","ts":"2024-06-05T13:18:14Z","msg":"giving up watch","error":"the server could not find the requested resource","resource":"projectcalico.org/v3, Resource=networkpolicies"}
```
We are not using neither of these crd in our cluster:
```
$ kubectl get crd | grep calico
$
$ kubectl get crd | grep cilium
$
```

# Environment
OS: Kubernetes (EKS) v1.29
Version:  quay.io/kubescape/synchronizer:v0.0.72
 
# Steps To Reproduce
Not sure how to reproduce it exactly, but basically we don't have any custom configuration on our kubescape:
```
clusterName: "my-cluster"
logger:
  level: error
account: "******"
server: api.armosec.io
credentials:
  cloudSecret: cloud-secret
capabilities:
  vulnerabilityScan: disable
kubescapeScheduler:
  scanSchedule: 0 3 * * 6
```

# Expected behavior
synchronizer pod should not restart in loop and output this error

# Actual Behavior
the one described above
