### ISSUE TITLE
Network policies not generated in kind and k3s

### ISSUE THREAD

**Issue by bharathvenkatrajan** [kubescape/kubescape#1823]
# Description

When running kubescape in-cluster mode in my local kind or k3s, I don't see network policies generated. Any help is much appreciated @matthyx @amitschendel 

# Environment

Mac M1 Max - 15.3.2

# Steps To Reproduce

1 . kind cluster setup, config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 44300
    protocol: TCP
- role: worker
```
2. Ran this command to create the kind cluster
```
kind create cluster --name=local-dev --config=newConfig.yaml
```
3. Two namespaces, two deployments that sends a curl request to the other:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: ping
---
apiVersion: v1
kind: Namespace
metadata:
  name: pong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-deployment
  namespace: pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: pong
        image: hashicorp/http-echo:latest
        args:
          - "-text=pong"
          - "-listen=:5678"
        ports:
          - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: pong-svc
  namespace: pong
spec:
  selector:
    app: pong
  ports:
  - protocol: TCP
    port: 5678
    targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
  namespace: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: curlimages/curl:latest
        command: [ "sh", "-c", "while true; do echo 'pinging pong'; curl -s http://pong-svc.pong:5678; echo; sleep 5; done" ]
```
4. I can see the output/log in the container, since there are no netpols configured currently.
5. Now, install kubescape via:
```
helm upgrade --install kubescape kubescape/kubescape-operator -n kubescape --create-namespace --set clusterName=kind-local-dev --set capabilities.continuousScan=enable --set capabilities.networkPolicyService=enable
```

# Expected behavior

`kubectl get generatednetworkpolicies -A ` returns the generated netpols for ping to reach pong.

# Actual Behavior

1. helm install using these flags: 
```
❯ helm upgrade --install kubescape kubescape/kubescape-operator -n kubescape --create-namespace --set clusterName=kind-local-dev --set capabilities.continuousScan=enable --set capabilities.networkPolicyService=enable

Release "kubescape" does not exist. Installing it now.
W0415 09:32:18.749389   86702 warnings.go:70] spec.template.metadata.annotations[container.apparmor.security.beta.kubernetes.io/node-agent]: deprecated since v1.30; use the "appArmorProfile" field instead
NAME: kubescape
LAST DEPLOYED: Tue Apr 15 09:32:17 2025
NAMESPACE: kubescape
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing kubescape-operator version 1.27.2.



View your image vulnerabilities scan summaries:
> kubectl get vulnerabilitymanifestsummaries -A

Detailed reports are also available:
> kubectl get vulnerabilitymanifests -A

kubescape-operator generates suggested network policies. To view them:
> kubectl get generatednetworkpolicies -n <namespace>
```

`kubectl get generatednetworkpolicies -A ` returns `no resources found`

2. All pods in the kubescape namespace are running - `node-agent` logs:
```
│ {"level":"info","ts":"2025-04-14T23:32:48Z","msg":"credentials loaded","accountLength":0}                                                                                                                                         │
│ {"level":"info","ts":"2025-04-14T23:32:48Z","msg":"Kubernetes mode is true"}                                                                                                                                                      │
│ {"level":"info","ts":"2025-04-14T23:32:48Z","msg":"starting health manager","port":7888}                                                                                                                                          │
│ W0414 23:32:48.495476    1614 client_config.go:667] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
│ {"level":"info","ts":"2025-04-14T23:32:48Z","msg":"waiting for storage to be ready","error":"the server is currently unable to handle the request (get applicationprofiles.spdx.softwarecomposition.kubescape.io)","retry in":"5s │
│ {"level":"info","ts":"2025-04-14T23:32:53Z","msg":"waiting for storage to be ready","error":"the server is currently unable to handle the request (get applicationprofiles.spdx.softwarecomposition.kubescape.io)","retry in":"5s │
│ time="2025-04-14T23:34:48Z" level=info msg="using the detected container runtime socket path from Kubelet's config: /run/containerd/containerd.sock"                                                                              │
│ {"level":"info","ts":"2025-04-14T23:34:48Z","msg":"IG Kubernetes client created","client":{"RuntimeConfig":{"Name":"containerd","SocketPath":"/host/run/containerd/containerd.sock","RuntimeProtocol":"cri","Extra":{"Namespace": │
│ {"level":"info","ts":"2025-04-14T23:34:48Z","msg":"detected container runtime","containerRuntime":"containerd"}                                                                                                                   │
│ {"level":"info","ts":"2025-04-14T23:34:49Z","msg":"start monitor on container","container ID":"109687fe74bf2dfc66e81011434ec64be3d8bc2e5a29278d5949fc159c8fcd73","k8s workload":"pong/pong-deployment-c9699d574-c6c8s/pong","Cont │
│ {"level":"info","ts":"2025-04-14T23:34:49Z","msg":"start monitor on container","container ID":"d9e28ac81143064c03eb969ae5fcb9f52222c79d4c2fac01be6e82279d1a8dfa","k8s workload":"ping/ping-deployment-7b994cc57f-zs6l8/ping","Con │
│ {"level":"info","ts":"2025-04-14T23:34:49Z","msg":"started syscall tracing"}                                                                                                                                                      │
│ {"level":"info","ts":"2025-04-14T23:34:49Z","msg":"started exec tracing"}                                                                                                                                                         │
│ {"level":"info","ts":"2025-04-14T23:34:49Z","msg":"started open tracing"}                                                                                                                                                         │
│ {"level":"info","ts":"2025-04-14T23:34:50Z","msg":"started dns tracing"}                                                                                                                                                          │
│ {"level":"info","ts":"2025-04-14T23:34:50Z","msg":"started network tracing"}                                                                                                                                                      │
│ {"level":"info","ts":"2025-04-14T23:34:51Z","msg":"started http tracing"}                                                                                                                                                         │
│ {"level":"info","ts":"2025-04-14T23:34:51Z","msg":"main container handler started"}
```

# Additional context
