### ISSUE TITLE
C-0012 detecting false positive environement variable which sets secret Path

### ISSUE THREAD

**Issue by thelooter** [kubescape/kubescape#1839]
# Description
When scanning resources which reference files mounted through a volumemount, but contain the `secret` string, are detected, even though they don't  present a security Risk

**Environment Variable Definition**:

```yaml
# ...
        - name: METALLB_ML_SECRET_KEY_PATH
          value: /etc/ml_secret_key
#...
```

**Volume Mount Definition**:

```yaml
# ...
        volumeMounts:
        - mountPath: /etc/ml_secret_key
          name: memberlist
          readOnly: true
#...
```

**Volume Definition**:

```yaml
# ...
      volumes:
      - name: memberlist
        secret:
          defaultMode: 420
          secretName: memberlist
#...
```

# Environment
OS: `Arch Linux ` 
Version: `3.0.34 ` 
 
# Steps To Reproduce
1. Deploy K3s with this Ansible Playbook, making sure metallb is enabled: https://github.com/techno-tim/k3s-ansible
2. Run `kubescape scan control C-0012 -v`
3.  See Result

# Expected behavior
This case not being raised as a security issue

# Actual Behavior
This case is being raised as a security issue

# Additional context
