### ISSUE TITLE
Image Scan Setup Failure - Authentication Required

### ISSUE THREAD

**Issue by erikbohnhorst** [kubescape/kubescape#498]
Hi Team,

I am trying to get Image Scanning to work but running into the below issue. Any idea? Do I need to modify the Helm Chart with my secret or anything else?

Thanks
```
07e2 exit code 256 :original error:: exit status 1
[0000] DEBUG Application config:
configpath: /etc/vuln-scan/anchore-resources/.grype/ranohecogadewosuferanohisotadenotehimohedorusoretomilubotecatehumecotefapusetaneta.yaml
output: json
outputtemplatefile: ""
scopeopt: Squashed
scope: Squashed
quiet: false
log:
  structured: false
  levelopt: trace
  level: trace
  filelocation: ""
clioptions:
  configpath: /etc/vuln-scan/anchore-resources/.grype/ranohecogadewosuferanohisotadenotehimohedorusoretomilubotecatehumecotefapusetaneta.yaml
  verbosity: 0
db:
  dir: /etc/vuln-scan/anchore-resources/db
  updateurl: https://toolbox-data.anchore.io/grype/databases/listing.json
  autoupdate: false
  validatebyhashonstart: false
dev:
  profilecpu: false
checkforappupdate: true
failon: ""
failonseverity: null
registry:
  insecure-skip-tls-verify: false
  insecure-use-http: false
  auth: []

[0000] DEBUG No new grype update available
[0000] DEBUG gathering packages
[0000] DEBUG loading DB
[0000] DEBUG image: source=OciRegistry location=sha256:53157464d691e3ceea0f55b28ce23151d5bd93b9ad8ea8296837d7c14e3507e2 from-lib=stereoscope
[0000] DEBUG pulling image info directly from registry image="sha256:53157464d691e3ceea0f55b28ce23151d5bd93b9ad8ea8296837d7c14e3507e2" from-lib=stereoscope
[0000] DEBUG no registry credentials configured, using the default keychain from-lib=stereoscope
[0001] ERROR failed to catalog: could not fetch image 'sha256:53157464d691e3ceea0f55b28ce23151d5bd93b9ad8ea8296837d7c14e3507e2': failed to get image descriptor from registry: GET https://index.docker.io/v2/library/sha256/manifests/53157464d691e3ceea0f55b28ce23151d5bd93b9ad8ea8296837d7c14e3507e2: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/sha256 Type:repository]]
```
