### ISSUE TITLE
C-0001 - Forbidden Container Registries False Positive

### ISSUE THREAD

**Issue by vidbregar** [kubescape/kubescape#589]
#### Issue description
C-0001 control should not fail for k8s objects that use images from Docker Hub if in `controls-inputs.json` `publicRegistries` and `untrustedRegistries` fields are set to an empty array.

#### Steps to reproduce the issue

- Create `controls-inputs.json`
```json
{
  "imageRepositoryAllowList": [
    "*.dkr.ecr.*.amazonaws.com",
    "k8s.gcr.io",
    "quay.io",
    "docker.io"
  ],
  "publicRegistries": [],
  "untrustedRegistries": []
}
```
-  Deploy example nginx
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```
- Run kubescape
``` bash
kubescape scan --controls-config controls-inputs.json --verbose control "Forbidden Container Registries"
```

#### What's the expected result?
Running the following command should not report any issues
```bash
kubescape scan --controls-config controls-inputs.json --verbose control "Forbidden Container Registries"
```

################################################################################
ApiVersion: apps/v1
Kind: Deployment
Name: nginx-deployment
Namespace: default

Controls: 1 (Failed: 1, Excluded: 0)

+----------+--------------------------------+------------------------------------+----------------------------------------+
| SEVERITY |          CONTROL NAME          |                DOCS                |         ASSISTANT REMEDIATION          |
+----------+--------------------------------+------------------------------------+----------------------------------------+
| Medium   | Forbidden Container Registries | https://hub.armosec.io/docs/c-0001 | spec.template.spec.containers[0].image |
+----------+--------------------------------+------------------------------------+----------------------------------------+

#### Additional details
Kubescape version: v2.0.166
k3d version v5.4.3
k3s version v1.23.6-k3s1 (default)
