### ISSUE TITLE
C-0078 - Images from allowed registry False Positive

### ISSUE THREAD

**Issue by vidbregar** [kubescape/kubescape#590]
#### Issue description
C-0078 control should not fail for k8s objects that use images from registries which are specified in `controls-inputs.json` `imageRepositoryAllowList` field. Control fails for images from Docker Hub, Quay.io, etc.

#### Steps to reproduce the issue

- Create `controls-inputs.json`
```json
{
  "imageRepositoryAllowList": [
    "*.dkr.ecr.*.amazonaws.com",
    "k8s.gcr.io",
    "quay.io",
    "docker.io"
  ],
  "publicRegistries": [],
  "untrustedRegistries": []
}
```
-  Deploy example nginx
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```
- Run kubescape
``` bash
kubescape scan --controls-config controls-inputs.json --verbose control "Images from allowed registry"
```

#### What's the expected result?
Running the following command should not report any issues
```bash
kubescape scan --controls-config controls-inputs.json --verbose control "Images from allowed registry"
```

################################################################################
ApiVersion: apps/v1
Kind: Deployment
Name: nginx-deployment
Namespace: default

Controls: 1 (Failed: 1, Excluded: 0)

+----------+------------------------------+------------------------------------+----------------------------------------+
| SEVERITY |         CONTROL NAME         |                DOCS                |         ASSISTANT REMEDIATION          |
+----------+------------------------------+------------------------------------+----------------------------------------+
| Medium   | Images from allowed registry | https://hub.armosec.io/docs/c-0078 | spec.template.spec.containers[0].image |
+----------+------------------------------+------------------------------------+----------------------------------------+

#### Additional details
Kubescape version: v2.0.166
k3d version v5.4.3
k3s version v1.23.6-k3s1 (default)
