### ISSUE TITLE
GitLab CI/CD intergration faied

### ISSUE THREAD

**Issue by oakgul1** [kubescape/kubescape#842]
# Describe the bug
i followed the instuctions ( https://hub.armosec.io/docs/gitlab ) to to integrate Kubescape to GitLab CI. 
failed with bash: line 66: /usr/local/bin/kubescape: No such file or directory
Any help?
![unknown](https://user-images.githubusercontent.com/114095478/191556286-244edb74-11fa-42db-ba95-d974b5f1b749.png)

**Comment by dwertent** [comment]
Thank for reporting this. It seems like the downloaded Kubescape binary cannot be saved in the path.
How about opening a feature request for creating a Kubescape GitLab job (similar to the [Kubescape GitHub actions](https://github.com/kubescape/github-action))

**Comment by oakgul1** [comment]
I did

**Comment by dwertent** [comment]
https://github.com/kubescape/github-action/issues/12

**Comment by jeanbritz** [comment]
Hi. I ran into the same issue. For now it seems that alpine does not pick up the `kubescape` binary for some reason. Maybe the binary is not in the correct format?

This has worked for me in the meantime:
```
kubescape:scan:
  image: ubuntu:latest
  needs: []
  script:
    - apt-get update && apt-get install curl -y
    - curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | bash
    - kubescape scan .
```

**Comment by mocdaniel** [comment]
If I may chime in here - the binary gets downloaded all right, the problem lies within the way it seems to be *built*. It tries to dynamically link libraries which are not installed on Alpine based images by default. You can verify this like so

```
❯ docker run -it --rm bash:latest bash
bash-5.2# apk add curl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20220614-r0)
(2/5) Installing brotli-libs (1.0.9-r6)
(3/5) Installing nghttp2-libs (1.47.0-r0)
(4/5) Installing libcurl (7.83.1-r4)
(5/5) Installing curl (7.83.1-r4)
Executing busybox-1.35.0-r17.trigger
Executing ca-certificates-20220614-r0.trigger
OK: 9 MiB in 22 packages
bash-5.2# curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | bash
Installing Kubescape...

######################################################################## 100.0%

Finished Installation.

bash: line 66: /usr/local/bin/kubescape: cannot execute: required file not found
bash-5.2# ldd $(which kubescape)
        /lib64/ld-linux-x86-64.so.2 (0x7f2caf61e000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f2caf61e000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f2caf61e000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f2caf61e000)
Error relocating /usr/local/bin/kubescape: __fprintf_chk: symbol not found
Error relocating /usr/local/bin/kubescape: __memcpy_chk: symbol not found
Error relocating /usr/local/bin/kubescape: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/kubescape: __vsnprintf_chk: symbol not found
Error relocating /usr/local/bin/kubescape: __strncpy_chk: symbol not found
Error relocating /usr/local/bin/kubescape: __snprintf_chk: symbol not found
Error relocating /usr/local/bin/kubescape: __printf_chk: symbol not found
bash-5.2#
``` 

Installing `gcompat` fixes this issue, so a working GitLab job definition should look something like this:

```yaml
scan-job:
  stage: scan
  image: bash:5.2.15@sha256:d2daf13cf80f3743960e3a5b64e66f0e7fcc904369eca3b94dc83c638a6595aa
  script:
  - apk add curl gcompat
  - curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | bash
  - kubescape scan .
```
