### ISSUE TITLE
Query about Excluding Cluster scoped resources when 'exclude-namespaces' flag is used

### ISSUE THREAD

**Issue by suhasgumma** [kubescape/kubescape#910]
Currently, Kubescape excludes cluster-scoped resources along with the provided namespaces when scanned with exclude-namespaces flag. 

When a user uses `--exclude-namespaces` flag, shouldn't we only exclude the mentioned namespaces and scan all others including cluster scope resources  (especially RBAC resources)?

Consider this scenario,

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: democrb
subjects:
- kind: ServiceAccount
  name: demosa
  apiGroup: ""
  namespace: demons
roleRef:
  kind: ClusterRole
  name: crdemo
  apiGroup: ""
```

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crdemo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
```

Suppose the user decided to exclude `kube-sysytem & kube-public` to avoid clutter. In that case, we would not be able to inform the user about the sub-optimal practice of granting all permissions.
